version: "3"

services:
  process-manager:
    build: .
    expose:
      - 8080
    volumes:
      - ./data.db:/go/src/build/data.db
  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - process-manager
    ports:
      - 8080:8080
